### ISSUE TITLE
RadioDSP_SDR_RX.

### ISSUE THREAD

**Issue by Haranochi** [gcallipo/RadioDSP_SDR_RX#1]
Ciao, voglio conoscere qualche dettaglio in più sul tuo progetto per costruirlo, dove posso ottenere una schema del progetto. Grazie mille.

José María

**Comment by gcallipo** [comment]
Hi, thanks for interesting in the project,
I'm working on It and I'm planning to add full descrptiption and schematics in the next weeks.
At the moment you can follows us in two group that we use to build the sdr, the group:.   
https://groups.io/g/keithsdr
And the Facebook group.   keiths_sdr
I'm working starting from an idea of the work that Keith, me and other ham radio fiends are started, Then create my own project with some extended functionalities and different layout.
I Hope  to see you in the groups .
Best 73 de Giuseppe Ik8yfw

**Comment by Haranochi** [comment]
Hi,
Thank you for responding quickly, I have requested to join the group https://groups.io/g/keithsdr and I await the approval of the moderator.
I follow your project with great interest. Thank.

José María
