### ISSUE TITLE
New questions.

### ISSUE THREAD

**Issue by Haranochi** [gcallipo/RadioDSP_SDR_RX#2]
Hi Giuseppe,
 When I got home from the Faculty I visited your github page and I verify that you put the diagrams of your project (test) of the sdr receiver that you have built. Thanks for the time and effort.

When I look at the .ino files in the src folder, I see two more folders, RadioDSP_SDR_RX and tests.

In the RDSP_general_includes.h file, lines 49, 50 and 51.

 // Define 3 buttons for menu operation
#define BUTTON_D2  2 // Switch 1
#define BUTTON_D3  6 // Encoder switch
#define BUTTON_D6  3 // Switch 2

Additional comments are notes to me.

In the test file, RadioDSP_SDR_RX_Conv.ino:

// Define 3 buttons for menu operation
#define BUTTON_D2  2
#define BUTTON_D3  3
#define BUTTON_D6  6

In the file RDSP_general_includes.h, BUTTON_D3 6 and BUTTON_D6 3, my question why you change those pins.

I have compiled with no errors, just two warnings, the RadioDSP_SDR_RX sketch. Now I just have to build it.

Another question why use teensy 4.0 and not 3.6, due to its higher speed ARM.

I want to try compiling the sketch for teensy 3.6, I have an unused one at home and an audio adapter board so I don't have to buy the teensy 4.0 and audio adapter boards for 4.0. or adapt the wiring of the audio adapter boards 3.6 to 4.0. I want to modify arm_math.h file from CMSIS library version 4.5.0, is it possible to do it? If possible I prefer that you do not tell me how, I want to do it myself, if it is not possible please tell me.

Regards,
José María

**Comment by gcallipo** [comment]
The tests dir Is Just a backup for some experiments you can skip It.  The project at the moment works on audiosdr library originally created for teensy 3.5/6, then I think that you don't have problems to recompile It on 3.6.  If you see some lack on running you can turn off the Convolutional and Noise reduction section to reduce load.
The project Is quite completed I've to adjust and fix some minor bug on menù and mybe to change the si5351  library for the best si5351mcu to reduce noise on frequency change.
That's all for now.
Thanks for your interest on project.
Best wishes G.
--
Inviato da Libero Mail per Android lunedì, 15 febbraio 2021, 11:12PM +01:00 da Haranochi  notifications@github.com :

**Comment by gcallipo** [comment]
For the CMSIS I don't try in this project. I worked on stm32 platform and changed also some versions, but here,  I don't know if an upgrade can create problems on original Teensy basic audio library or the audiosdr. Check both the library references: Teensy audio library and the audio are lib. 
G.
--
Inviato da Libero Mail per Android lunedì, 15 febbraio 2021, 11:12PM +01:00 da Haranochi  notifications@github.com :
